### ISSUE TITLE
Total attachments size not working

### ISSUE THREAD

**Issue by wbrauneis** [AndreyVMarkelov/jira-prometheus-exporter#10]
The total attachments size gauge in version 1.0.10 steadily reports a value of 0 due to a commented section in the respective part of the source code.

Please note that this is very much appreciated, at least from our perspective, as this new "feature" rendered the plugin practically unusable in our JIRA installation due to the huge number of attachments (prometheus queries took several seconds for collecting the data per each request).

**Comment by AndreyVMarkelov** [comment]
Hello. Can you please enable debug to plugin class. It will print the time.
Can we go to chat?

15 Янв 2018 г. 19:51 пользователь "wbrauneis" <notifications@github.com>
написал:

**Comment by AndreyVMarkelov** [comment]
Sorry guys. I dont have the very large installation. If somebody have the
biggest stage we can test few new features togethwr to sure that all is
working

15 Янв 2018 г. 19:59 пользователь "Andrey Markelov" <
andrey.v.markelov@gmail.com> написал:

**Comment by wbrauneis** [comment]
Hi,

the attached screenshot shows the request times for our JIRA instance. At
about 10:02 version 1.0.8 of the plugin was activated and request times to
the plugin increased considerably.

Kind regards,
Wolfgang




2018-01-15 17:59 GMT+01:00 Andrey Markelov <notifications@github.com>:

**Comment by wbrauneis** [comment]
The attached screenshot shows request times for our JIRA instance. At about 10:02, version 1.0.8 of the plugin was activated and request times to the plugin increased considerably, at  10:41 we deactivated the plugin.

![grafana_-_jira_metrics](https://user-images.githubusercontent.com/4495594/34954030-2ec1e50e-fa1f-11e7-8737-03e4c315b1a2.png)

**Comment by AndreyVMarkelov** [comment]
With version 10 become better?

15 Янв 2018 г. 20:10 пользователь "wbrauneis" <notifications@github.com>
написал:

**Comment by wbrauneis** [comment]
Yes it did, I guess this commit here https://github.com/AndreyVMarkelov/jira-prometheus-exporter/commit/14c326208d6648b0492de6306e3519589cd3a6a6 deactivated the code to calculate the attachments size altogether...

**Comment by AndreyVMarkelov** [comment]
What do you think if i do calculation async? So rin some in backround with
some rate f.e. once 1 minutes and collect will take the last result? Not
fully accurate but I believe without problems

15 Янв 2018 г. 20:15 пользователь "wbrauneis" <notifications@github.com>
написал:

**Comment by wbrauneis** [comment]
Does Jira expose the file size per attachment using the attachment-manager component? Maybe this would allow for a faster alternative implementation.

Async traversal of the attachments directory certainly is a way to go. However it would be nice if the interval time could be configured in the plugin configuration.

**Comment by AndreyVMarkelov** [comment]
Yes. No api. I will check performance direct db call but they will be async
too

15 Янв 2018 г. 20:24 пользователь "wbrauneis" <notifications@github.com>
написал:

**Comment by wbrauneis** [comment]
Sounds great, looking forward to the upcoming release. Great and very helpful plugin!

**Comment by AndreyVMarkelov** [comment]
I will open possible implementation issues tomorrow. Do you use bamboo?

15 Янв 2018 г. 20:37 пользователь "wbrauneis" <notifications@github.com>
написал:

**Comment by wbrauneis** [comment]
No, bamboo is not yet on our list of tools we use for development.
