### ISSUE TITLE
The web-section in admin gui can not be wrapped.

### ISSUE THREAD

**Issue by hfuhuang** [AndreyVMarkelov/jira-prometheus-exporter#14]
In /jira-prometheus-exporter/src/main/resources/atlassian-plugin.xml, the label of web-section is too long and it can not be wrapped since it is a section.
\<web-section name="Security Token Admin Section" key="prom-for-jira-exporter-admin-section" location="admin_plugins_menu"\>
        \<label key="ru.andreymarkelov.atlas.plugins.promjiraexporter.section"/>
    \</web-section>

It would be nice if the label is shorten to "promjiraexporter"

**Comment by AndreyVMarkelov** [comment]
@hfuhuang Hi, can you attach screenshot please?

**Comment by hfuhuang** [comment]
@AndreyVMarkelov I think you have change it to "Prometheus Exporter". Now it looks better. This ticket is closed. 
But the jira_maintenance_expiry_days_gauge returns always 0 instead of the real number. I will create another issue for it.
