### ISSUE TITLE
Leaking metrics

### ISSUE THREAD

**Issue by trnl** [AndreyVMarkelov/jira-prometheus-exporter#16]
Following 2 metrics producing very high number of series on the server. 
```
jira_issue_update_count{projectKey="y",issueKey="y-16364",eventType="Issue Updated",username="z",} 1.0
jira_total_sessions_gauge{ip="x,y",username="p",requestsCount="168",} 1.0
```

One of the first problems is `jira_total_sessions_gauge` where `requestsCount` is used as label, not a value. Due to different 'requestsCount' all the values are set to '1.0' `ip` should also be split up, or fully dropped. 

`jira_issue_update_count` have user x ticket x eventType cardinality. It means in the system with 1k users and 1k tickets you'lll have 5 million time series which will easily kill any Prometheus.

**Comment by trnl** [comment]
Hmm, I don't see this in the code.

**Comment by AndreyVMarkelov** [comment]
Hi. Which plugin version is used?

19 Фев 2018 г. 20:37 пользователь "Uladzimir Mihura" <
notifications@github.com> написал:

**Comment by AndreyVMarkelov** [comment]
@trnl I will fix jira_issue_update_count. You are right. WIll remove issueKey. I added by mistake.

**Comment by trnl** [comment]
Now we use 1.0.7

**Comment by AndreyVMarkelov** [comment]
Done
