### ISSUE TITLE
jira_maintenance_expiry_days_gauge return 0.0 instead of the real number.

### ISSUE THREAD

**Issue by hfuhuang** [AndreyVMarkelov/jira-prometheus-exporter#18]
# HELP jira_maintenance_expiry_days_gauge Maintenance Expiry Days Gauge
# TYPE jira_maintenance_expiry_days_gauge gauge
jira_maintenance_expiry_days_gauge 0.0
![screen shot 2018-03-06 at 16 37 35](https://user-images.githubusercontent.com/230489/37042054-ed98aebc-215d-11e8-8c78-707fda3861f8.png)

**Comment by AndreyVMarkelov** [comment]
Hello. What is type of license?

6 Мар 2018 г. 18:46 пользователь "hfuhuang" <notifications@github.com>
написал:

**Comment by hfuhuang** [comment]
@AndreyVMarkelov it is a JIRA Dev license. Maybe that is reason. Then I will close the issue.

**Comment by AndreyVMarkelov** [comment]
Allright. It is true

6 Мар 2018 г. 18:50 пользователь "hfuhuang" <notifications@github.com>
написал:

**Comment by hfuhuang** [comment]
@AndreyVMarkelov the problem is still there. 
JIRA Software 7.4.1
Maintenance expires    17.04.2019

But the jira_maintenance_expiry_days_gauge was turned as 0.0

Can you check the following code with JIRA 7.4.1?
// license
        SingleProductLicenseDetailsView licenseDetails = jiraApplicationManager.getPlatform().getLicense().getOrNull();
        if (licenseDetails != null) {
            maintenanceExpiryDaysGauge.set(DAYS.convert(licenseDetails.getMaintenanceExpiryDate().getTime() - System.currentTimeMillis(), MILLISECONDS));
            licenseExpiryDaysGauge.set(DAYS.convert(licenseDetails.getLicenseExpiryDate().getTime() - System.currentTimeMillis(), MILLISECONDS));
            allowedUsersGauge.set(licenseDetails.getNumberOfUsers());
        }

**Comment by AndreyVMarkelov** [comment]
Check with latest version please

**Comment by hfuhuang** [comment]
@AndreyVMarkelov I have tested with the latest version, and it does not work still. I think the license management API did not work in JIRA. In Confluence, the API used works.

**Comment by AndreyVMarkelov** [comment]
Please screenshot me your admin license page.

пн, 14 Май 2018 г., 17:51 hfuhuang <notifications@github.com>:

**Comment by hfuhuang** [comment]
@AndreyVMarkelov Is it possible to have a JUNIT Test? 
I think it has something to do with JIRA UPM, especially if the JIRA is behind a proxy and the UPM can not connect to the Atlassian Market Place.
<img width="1072" alt="screen shot 2018-05-15 at 09 24 16" src="https://user-images.githubusercontent.com/230489/40055711-2a422d62-5849-11e8-912f-754fab6a5f7c.png">
<img width="1084" alt="screen shot 2018-05-15 at 09 57 11" src="https://user-images.githubusercontent.com/230489/40055722-35d022c4-5849-11e8-9ff5-162514e225b6.png">
