### ISSUE TITLE
Exclude some metrics

### ISSUE THREAD

**Issue by hfuhuang** [AndreyVMarkelov/jira-prometheus-exporter#23]
Hi, Is it possible to exclude some metrics, for example, not expose the metric issueUpdateCounter?

**Comment by aviorma** [comment]
you cant ask to exclude metrics, maybe that metric is good for other people

**Comment by AndreyVMarkelov** [comment]
Hi. It is possible to add query filters. I will add notes to the doc on
Monday

сб, 14 Апр 2018 г., 23:51 aviorma <notifications@github.com>:

**Comment by hfuhuang** [comment]
@AndreyVMarkelov Thanks! Has an example of query filter been added in the wiki page?

**Comment by hfuhuang** [comment]
with &name[]=...
