### ISSUE TITLE
Possibility of disabling attachment size calculation

### ISSUE THREAD

**Issue by johnwyde** [AndreyVMarkelov/jira-prometheus-exporter#28]
Hi there!

Is it possible to disable attachments size calculation?
As if we don't need to have this data but it sometimes slows down our instance with large number of attachments.

**Comment by Alexander-Moroz** [comment]
+1

**Comment by AndreyVMarkelov** [comment]
@johnwyde will be done next release by settings delay to zero

**Comment by AndreyVMarkelov** [comment]
Now if set 0 it will disable it.

**Comment by johnwyde** [comment]
Sweet! Thnx!
