### ISSUE TITLE
Metrics for non-existing endpoints

### ISSUE THREAD

**Issue by flamein** [AndreyVMarkelov/jira-prometheus-exporter#37]
We encountered the issue that the exporter creates a whole bunch of metrics for ALL paths being called from the browser, even the non existing ones, like `/admin.php`, `../../../../etc/shadow`, `../../../etc/shadow` and so on and so forth.

Any instance that is listening on the internet will inevitably get scanned by hundreds of bots, completely overwhelming both JIRA and the prometheus server when metrics are being crawled.

This could very well be a cause for https://github.com/AndreyVMarkelov/jira-prometheus-exporter/issues/36 as well.

We had to disable the exporter because it was destroying our prometheus and JIRA

**Comment by AndreyVMarkelov** [comment]
Hello. Actually it is new bug. Didnt see before on many installations. Can
you give me please your real urls which comes to jira? Some tricky proxy?

чт, 6 дек. 2018 г., 17:23 flamein notifications@github.com:

**Comment by AndreyVMarkelov** [comment]
In progress

**Comment by AndreyVMarkelov** [comment]
@flamein do you still have it?
