### ISSUE TITLE
Some of the the metrics are not available for my Jira Instance 

### ISSUE THREAD

**Issue by vivekj11** [AndreyVMarkelov/jira-prometheus-exporter#39]
Hi,

I have configured my Jira instance to provide metrics to Prometheus and its is working fine. But I have one issue, some of the metrics as I can see in example like Login/Logout count, issues count per project  are not available to me. 
I have done the exact thing as directed. 
Exporter version- 1.0.20
Jira Version- 7.3.9

Can someone let me know why is it happening? Am I missing something.
Kindly let me know if some other details are required from my side.

**Comment by AndreyVMarkelov** [comment]
Will be fixed soon

**Comment by ohanainfo** [comment]
Hello, I got 0 on attachment gauge for Jira (see below). Any hint to fix this?
jira_total_attachment_size_gauge 0.0

**Comment by AndreyVMarkelov** [comment]
@vivekj11 @ohanainfo  Hello, please, check with the newest version

**Comment by vivekj11** [comment]
@AndreyVMarkelov 
Thanks for the update. :)
I will check it after sometime (during the maintenance window of our cluster.) Will let know in case of any further help.
