### ISSUE TITLE
Don't open Configuration page for plugin

### ISSUE THREAD

**Issue by zakabluk** [AndreyVMarkelov/jira-prometheus-exporter#42]
Hi! maybe you can help me, but I have got an old version Jira 6.2. So I have to installed plugin version Version: 1.0.2 .
Jira is 32-bit and working on windows. 
When I tried click Configure bottom I have had error. Log 
[https://pastebin.com/nZDwqGS8](url)

Maybe is there approaches in the world which can help me?

**Comment by AndreyVMarkelov** [comment]
@zakabluk  Please try with the latest version
