### ISSUE TITLE
jira_license_expiry_date not shown

### ISSUE THREAD

**Issue by lmeyemezu** [AndreyVMarkelov/jira-prometheus-exporter#45]
Hi,
jira_license_expiry_date_gauge return 0.0 but jira_maintenance_expiry_days_gauge shows correct number.
Regards

**Comment by AndreyVMarkelov** [comment]
Hmm. Could you contact me directly andrey.v.markelov@gmail.com. I will help you. I think you have licences which I never tryed reproduce.

**Comment by AndreyVMarkelov** [comment]
Done
