### ISSUE TITLE
missing some metrics

### ISSUE THREAD

**Issue by Xfireman** [AndreyVMarkelov/jira-prometheus-exporter#48]
My metrics only include jvm。
Exporter version- 1.0.22
Jira Version- 8.0.1
just as：
![image](https://user-images.githubusercontent.com/14049712/54898322-c41ace80-4f06-11e9-9ac7-61d1b29feea8.png)

**Comment by Rohlik** [comment]
I can confirm this. We also have just jvm_* metrics exported.

Using Jira 8.0.2 and latest Jira exporter.

**Comment by dsmorse** [comment]
I can confirm the above as well on 8.0.2 I see an error in the JIRA log:

2019-04-03 13:10:50,746 http-nio-8080-exec-11 ERROR anonymous 790x43541x1 - 10.1.2.61,172.18.0.6 /plugins/servlet/prometheus/metrics [r.a.a.p.promjiraexporter.service.MetricCollectorImpl] Error collect prometheus metrics
java.lang.NoSuchMethodError: com.atlassian.application.api.PlatformApplication.getLicense()Lcom/atlassian/fugue/Option;

I'll try to see if I can find the correct chunk of code for a fix.

**Comment by dsmorse** [comment]
I can confirm the fugue error is part of the breaking API changes in 8.x - https://confluence.atlassian.com/adminjiraserver/end-of-support-announcements-938846831.html#Endofsupportannouncements-fugue

**Comment by AndreyVMarkelov** [comment]
Done
