### ISSUE TITLE
What happened to Jira Prometheus Exporter regarding Jira 8.1?

### ISSUE THREAD

**Issue by pdfoerster** [AndreyVMarkelov/jira-prometheus-exporter#49]
Hi,
I did a test upgrade to Jira 8.1 and noticed that the Jira Prometheus Export plugin is not compatible. However, when I was trying to check for a new compatible version at the marketplace https://marketplace.atlassian.com/apps/1217960/prometheus-exporter-for-jira/version-history there is a message:
"This app provides core functionality to one or more Atlassian products"

What happened with the plugin and the marketplace listing?
Has it been integrated with Jira Core?

Kind regards,
Patrice

**Comment by AndreyVMarkelov** [comment]
Done
