### ISSUE TITLE
Add product labels to jira_active_users_gauge metric

### ISSUE THREAD

**Issue by chrisipa** [AndreyVMarkelov/jira-prometheus-exporter#53]
Hello everyone,

the problem with the current metric **jira_active_users_gauge** is, that it does not distinguish between the different JIRA products like Software and Service Desk.

Here's an example:

If you have 478 active JIRA Software users and 22 active JIRA Service Desk users the **jira_active_users_gauge** metric will report 500 users.

So today it is not possible to create prometheus alerts based on license usage of a product. At the moment we are using this query to send alerts if the JIRA license usage is higher than 80%:

```
jira_active_users_gauge{job="jira"} / ignoring(licenseType) jira_allowed_users_gauge{licenseType="JIRA Software"} * 100 > 80
```
My suggestion would be to add labels for the products just like for the **jira_allowed_users_gauge** metric:

```
jira_active_users_gauge{licenseType="JIRA Software"}
jira_active_users_gauge{licenseType="JIRA Service Desk"}
```
What do you think? Does this sound reasonable?

Best regards
Chris

**Comment by AndreyVMarkelov** [comment]
I have added labels in version 31

Also for some old versions upon I have kept real user count for platform

**Comment by chrisipa** [comment]
That's really great news. Thanks for your help.
