### ISSUE TITLE
Metrics for Data Center

### ISSUE THREAD

**Issue by diverser** [AndreyVMarkelov/jira-prometheus-exporter#7]
Is it possible to get metrics from all DC node as labels
Cause now, we scrape each node per ip, and got common duplicated metrics
I think it will be easier to scrape one stable node and get metrics for all others, than scrape n nodes

**Comment by AndreyVMarkelov** [comment]
For datacenter, please, use config scrape metrics. For example:
```
...
- targets: ['localhost:9090', 'localhost:9191']
labels:
    nodeId: node001
    ip: host1
...
```
Every instance should own metrics.

**Comment by AndreyVMarkelov** [comment]
@cowmix I will be happy if you do PR.
