### ISSUE TITLE
Add license metrics

### ISSUE THREAD

**Issue by xtimon** [AndreyVMarkelov/jira-prometheus-exporter#9]
Could you please add license metrics such as:

- current number of users
- maximum number of users
- number of days before maintenance expiry

**Comment by AndreyVMarkelov** [comment]
Hey. Done. See:
# HELP jira_all_users_gauge All Users Gauge
# TYPE jira_all_users_gauge gauge
jira_all_users_gauge 1.0
# HELP jira_active_users_gauge Active Users Gauge
# TYPE jira_active_users_gauge gauge
jira_active_users_gauge 1.0
# HELP jira_allowed_users_gauge Allowed Users Gauge
# TYPE jira_allowed_users_gauge gauge
jira_allowed_users_gauge -1.0
# HELP jira_maintenance_expiry_days_gauge Maintenance Expiry Days Gauge
# TYPE jira_maintenance_expiry_days_gauge gauge
jira_maintenance_expiry_days_gauge 3.0
